### PR TITLE
Allow explicit use of builders and access to raw data buffers

### PR DESCRIPTION
**Pull request by hassila**
See commit comment https://github.com/hassila/FlatBuffersSwift/commit/017740e97039d19334b2396b8eb464ec5add321a for details, but the TL;DR, "10% encoding performance by optional manual reuse of builders + added raw access to buffer data when needed".

bench.swift diffs outlines the minor codegen changes needed to support it.

### CODE REVIEW

**Comment by hassila** [comment]
I can't get the CI to build as the codegen overwrites the manually adjuster files as part of the build process...

**Comment by mzaks** [comment]
could you please comment out the `generate` step in `.travis.yml` file.
It should look than something like:

```
language: objective-c
osx_image: xcode7.3
script:
#  - echo -en "travis_fold:start:generate\r"
#  - sh generate.sh
#  - echo -en "travis_fold:end:generate\r"
  - echo -en "travis_fold:start:unit_test\r"
  - xcodebuild test -project FlatBuffersSwift.xcodeproj -scheme FlatBuffersSwift ONLY_ACTIVE_ARCH=NO
  - echo -en "travis_fold:end:unit_test\r"
  - echo -en "travis_fold:start:build_perf_test\r"
  - xcodebuild -project FlatBuffersSwift.xcodeproj -scheme FlatBuffersPerformanceTestDesktopOptimized ONLY_ACTIVE_ARCH=NO -derivedDataPath result/
  - echo -en "travis_fold:end:build_perf_test\r"
  - ./result/Build/Products/Release/FlatBuffersPerformanceTestDesktop
```

I just want to get into the flow and have a history of builds, with the history of performance measurements.

**Comment by hassila** [comment]
Ok, gave it a spin in https://github.com/hassila/FlatBuffersSwift/commit/449badf38d90bf4c0d401569c5a00b5ffced1407  - let's see how it works out.

**Comment by hassila** [comment]
Ok, all good now...

**Comment by mzaks** [comment]
Cool, thank you!

**Comment by hassila** [comment]
> I just want to get into the flow and have a history of builds, with the history of performance measurements.

I think that is very good, but the question is whether Travis actually guarantees hardware that is identical between runs and is dedicate so the numbers will be comparable...

**Comment by mzaks** [comment]
True, but even if we have tot take it with a grain of salt, could still be useful

**Pull request merged**
