### PR TITLE
Fix memory leaks in FlatBufferBuilder

### PR DESCRIPTION
**Pull request by hassila**
Added missing deinit to reclaim allocated memory by builder.

### CODE REVIEW

**Comment by hassila** [comment]
Also added a fix for the excessive memory consumption for the eager test run in 6caf751 now making it stable. For the lazy run there seems to be a retain cycle still causing it to grow to 1GB+ with 1M iterations (https://github.com/mzaks/FlatBuffersSwift/issues/21)...

**Comment by hassila** [comment]
Also to clarify, the performance tests were run with everything built with optimization (including the framework).

**Comment by mzaks** [comment]
I am not sure about 
`let buf = Array(value.utf8)`
I think from my previous benchmarking 
`let buf = value.cStringUsingEncoding(NSUTF8StringEncoding)!`
was faster. 
Are there some other implication why you switched to `value.utf8`?

**Comment by hassila** [comment]
I got the same when running with non-optimized debug code, but enabling a release build I got different results - including fixing the excessive memory usage, see commit comment https://github.com/mzaks/FlatBuffersSwift/pull/20/commits/6caf751c6080dd4c7be68cb9146bf59f2d9df298 for more details on the improvement that change gave.

**Comment by hassila** [comment]
(most of the performance gain is likely due to the great reduction in memory usage)

**Pull request merged**
